# grabbing the base image
FROM postgres:latest

# name of the table
ENV POSTGRES_DB=foodmenu

# name of the postgres user
ENV POSTGRES_USER=postgres

# password here
ENV POSTGRES_PASSWORD=password123

# expose sql port
EXPOSE 5432

# not entry point necessary here like I would need for the application, as of right now


# docker build --no-cache -t foodmenu_db:v1 -f Dockerfile.db .   
# docker run -d --name foodmenu_db_container --network foodmenu-network foodmenu_db:v1