version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: on-failure:10
    environment:
    - PYTHONUNBUFFERED=1

  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports:
    - 5433:5432

volumes:
  foodapp-volume:
    external: true