apiVersion: v1
kind: Service
metadata:
  name: internetportopening
spec:
  type: NodePort
  selector:
    app: foodmenu-web
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 3000
      # targetport is what the node will target on the container
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
      # nodePort can possiblbe commented out....
      protocol: TCP