name: ci

on:
  push:
    branches:
      - "gha-create-container"

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
# will update the branch later; for now I just want to see the containers created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          role-to-assume: arn:aws:iam::370584750074:role/Github_Action_Assume_Role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        # uses: actions/checkout@v3
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: foodmenu
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile.app -t $REGISTRY/$IMAGE_TAG:app .
          # docker build -f Dockerfile.db -t $REGISTRY/db:$IMAGE_TAG .



          # echo $REGISTRY
          # echo $REPOSITORY
          # echo "it's failing here 1"
          # docker build -f Dockerfile.app -t $REGISTRY/app:$IMAGE_TAG .
          # echo "it's failing here 2"
          # docker build -f Dockerfile.db -t $REGISTRY/db:$IMAGE_TAG .
          # echo "it's failing here 3"
          # docker push $REGISTRY/app:$IMAGE_TAG
          # echo "it's failing here 4"
          # docker push $REGISTRY/db:$IMAGE_TAG
          # echo "it all passed!"
# docker build or docker compose build github actions troubleshooting//multiple images


# - name: Build docker images
#   Id: build-image
#   run: | 
#     echo ---Building images and starting up docker---
#     {{docker build [image-url] or docker-compose -f \
#     [docker-compose file] up -d }}
#     echo ---Containers up—
# try again maybe github was down
